tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "bat"
brew "git"
brew "httpie"
brew "exa"

cask "alfred"
cask "android-studio"
cask "google-chrome"
cask "rectangle"
cask "visual-studio-code"
cask "dropbox"
